### ISSUE TITLE
error while compiling pixel-Pie rom 

### ISSUE THREAD

**Issue by rohit12043-zz** [Sksbss/android_device_xiaomi_santoni#2]
Error while building rom

ninja: no work to do.
[1/1] /home/rohit/pe/out/soong/.bootstrap/bin/soong_build /home/rohit/pe/out/soong/build.ninja
Environment variable BUILD_NUMBER was modified (de0bd033c6 => 61525cc8cd), regenerating...
/home/rohit/pe/out/build-aosp_a6000.ninja is missing, regenerating...
[511/898] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[898/898] including vendor/qcom/opensource/rcs-service/Android.mk ...
device/lenovo/a6000/camera/QCamera2/HAL/Android.mk: error: camera.msm8916 (SHARED_LIBRARIES android-arm) missing libqdMetaData (SHARED_LIBRARIES android-arm)
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:837: error: exiting from previous errors.
22:48:45 ckati failed with: exit status 1

solution please.

**Comment by SonalSingh18** [comment]
First genuine suggestion leave compiling.....

2nd
Why are u using santoni's Device tree for compiling pixel pie for lenovo a6000??

Do u even know what u r doing??

**Comment by rohit12043-zz** [comment]
Sorry I was in Hurry so I posted wrong error. first I tried for lenovo a6000 with lenovo a6000 device tree, it failed. then I tried for redmi 4 but it also failed

**Comment by ghostrider-reborn** [comment]
Okay @rohit12043 now try for beryllium, whyred, X00TD, jasmine, land and maybe enchilada too. Hope you succeed and stuff those ROMs in your ass !
